version: '3.9'
services:
  api_gatway:
    image: devopsfaith/krakend:2.0.0
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - product_service
      - order_service
    ports:
      - "8080:8081"
  product_service:
    build:
      context: ./../ada-product-service
    container_name: product_service_ct
    ports:
      - "5000:5000"
  order_service:
    build:
      context: ./../order_service_v2
    container_name: order_service_ct
    ports:
      - "5001:5000"
